---
title: "[ESC] Bayes Week6 HW"
author: "SonJiwoo"
date: "`r Sys.Date()`"
output:
  pdf_document: null
  latex_engine: xelatex
mainfont: NanumGothic  
---

# 1. Poisson Regression
```{r}
#### Sparrow data
load("data/sparrows.RData")  
fledged<-sparrows[,1] ; age<-sparrows[,2] ; age2<-age^2
```

```{r include=FALSE}
#### Grid-based posterior approximation
p<-3
beta0<-rep(0,p)
S0<-diag( rep(100,3))
gs<-100
LPB<-array(0,dim=rep(gs,p))

beta1<-seq(.27-1.75,.27+1.75,length=gs)
beta2<-seq(.68-1.5,.68+1.5,length=gs)
beta3<-seq(-.13-.25,-.13+.25,length=gs)

beta1<-seq(.27-2.5,.27+2.5,length=gs)
beta2<-seq(.68-2,.68+2,length=gs)
beta3<-seq(-.13-.5,-.13+.5,length=gs)

for(i in 1:gs) { for(j in 1:gs) { for(k in 1:gs) {
  theta<-beta1[i]+beta2[j]*age+beta3[k]*age^2
  LPB[i,j,k]<-dnorm(beta1[i],beta0[1],sqrt(S0[1,1]),log=TRUE)  +
    dnorm(beta2[j],beta0[2],sqrt(S0[2,2]),log=TRUE)  +
    dnorm(beta3[k],beta0[3],sqrt(S0[3,3]),log=TRUE)  +
    sum( dpois(fledged,exp(theta),log=TRUE )  )
}} 
  # cat(i,"\n")
}

PB<-exp( LPB - max(LPB) )
PB<-PB/sum(PB)

PB1<-apply(PB,1,sum)
PB2<-apply(PB,2,sum)
PB3<-apply(PB,3,sum)
PB23<-apply(PB,c(2,3),sum)

#### Back to sparrow data
fit.mle<-glm(fledged~age+age2,family="poisson")
summary(fit.mle)

y<-fledged ; X<-cbind(rep(1,length(y)),age,age^2)
yX<-cbind(y,X)
colnames(yX)<-c("fledged","intercept","age","age2") 

n<-length(y) ; p<-dim(X)[2]

pmn.beta<-rep(0,p)
psd.beta<-rep(10,p)

var.prop<- var(log(y+1/2))*solve( t(X)%*%X )
beta<-rep(0,p)
S<-10000
BETA<-matrix(0,nrow=S,ncol=p)
ac<-0
set.seed(1)

## rmvnorm function for proposals
rmvnorm<-function(n,mu,Sigma)
{ # samples from the multivariate normal distribution
  E<-matrix(rnorm(n*length(mu)),n,length(mu))
  t(  t(E%*%chol(Sigma)) +c(mu))
}

## MCMC
for(s in 1:S) {
  
  #propose a new beta
  
  beta.p<- t(rmvnorm(1, beta, var.prop ))
  
  lhr<- sum(dpois(y,exp(X%*%beta.p),log=T)) -
    sum(dpois(y,exp(X%*%beta),log=T)) +
    sum(dnorm(beta.p,pmn.beta,psd.beta,log=T)) -
    sum(dnorm(beta,pmn.beta,psd.beta,log=T))
  
  if( log(runif(1))< lhr ) { beta<-beta.p ; ac<-ac+1 }
  
  BETA[s,]<-beta
}
cat(ac/S,"\n")

library(coda)
apply(BETA,2,effectiveSize)
```


### Figure 10.5
```{r}
#### Figure 10.5 
par(mar=c(2.75,2.75,.5,.5),mgp=c(1.7,.7,0))
par(mfrow=c(1,3))
blabs<-c(expression(beta[1]),expression(beta[2]),expression(beta[3]))
thin<-c(1,(1:1000)*(S/1000))
j<-3
plot(thin,BETA[thin,j],type="l",xlab="iteration",ylab=blabs[j])
abline(h=mean(BETA[,j]) )

acf(BETA[,j],ci.col="gray",xlab="lag")
acf(BETA[thin,j],xlab="lag/10",ci.col="gray")
```

### Figure 10.6
```{r}
#### Figure 10.6
par(mar=c(2.75,2.75,.5,.5),mgp=c(1.7,.7,0))
par(mfrow=c(1,3))

plot(beta2,PB2*length(beta2)/(max(beta2)-min(beta2)) ,type="l",xlab=expression(beta[2]),ylab=expression(paste(italic("p("),beta[2],"|",italic("y)"),sep="") ) ,lwd=2,lty=2,col="gray")
lines(density(BETA[,2],adj=2),lwd=2)

plot(beta3,PB3*length(beta3)/(max(beta3)-min(beta3)),type="l",xlab=expression(beta[3]),ylab=expression(paste(italic("p("),beta[3],"|",italic("y)"),sep="") ),lwd=2,col="gray",lty=2)
lines(density(BETA[,3],adj=2),lwd=2)

Xs<-cbind(rep(1,6),1:6,(1:6)^2) 
eXB.post<- exp(t(Xs%*%t(BETA )) )
qE<-apply( eXB.post,2,quantile,probs=c(.025,.5,.975))

plot( c(1,6),range(c(0,qE)),type="n",xlab="age",
      ylab="number of offspring")
lines( qE[1,],col="black",lwd=1)
lines( qE[2,],col="black",lwd=2)
lines( qE[3,],col="black",lwd=1)
```

# 2. Regression Model with Autocorrelation Errors
```{r}
#### Ice core example
load("data/icecore.RData")
```

```{r include=FALSE}
#### Starting values for MCMC
n<-dim(icecore)[1]
y<-icecore[,3]
X<-cbind(rep(1,n),icecore[,2])
DY<-abs(outer( (1:n),(1:n) ,"-"))

lmfit<-lm(y~-1+X)
beta<-lmfit$coef
s2<-summary(lmfit)$sigma^2
phi<-acf(lmfit$res,plot=FALSE)$acf[2]
nu0<-1 ; s20<-1 ; T0<-diag(1/1000,nrow=2)


## MCMC - 1000 scans saving every scan
set.seed(1)
S<-1000 ; odens<-S/1000
OUT<-NULL ; ac<-0 ; par(mfrow=c(1,2))
for(s in 1:S)
{
  
  Cor<-phi^DY  ; iCor<-solve(Cor)
  V.beta<- solve( t(X)%*%iCor%*%X/s2 + T0)
  E.beta<- V.beta%*%( t(X)%*%iCor%*%y/s2  )
  beta<-t(rmvnorm(1,E.beta,V.beta)  )
  
  s2<-1/rgamma(1,(nu0+n)/2,(nu0*s20+t(y-X%*%beta)%*%iCor%*%(y-X%*%beta)) /2 )
  
  phi.p<-abs(runif(1,phi-.1,phi+.1))
  phi.p<- min( phi.p, 2-phi.p)
  lr<- -.5*( determinant(phi.p^DY,log=TRUE)$mod -
               determinant(phi^DY,log=TRUE)$mod  +
               sum(diag( (y-X%*%beta)%*%t(y-X%*%beta)%*%(solve(phi.p^DY) -solve(phi^DY)) ) )/s2 )
  
  if( log(runif(1)) < lr ) { phi<-phi.p ; ac<-ac+1 }
  
  if(s%%odens==0)
  {
    # cat(s,ac/s,beta,s2,phi,"\n") ;
    OUT<-rbind(OUT,c(beta,s2,phi))
  }
}

OUT.1000<-OUT
library(coda)
apply(OUT.1000,2,effectiveSize )


## MCMC - 25000 scans saving every 25th scan
set.seed(1)
S<-25000 ; odens<-S/1000
OUT<-NULL ; ac<-0 ; par(mfrow=c(1,2))
for(s in 1:S)
{
  
  Cor<-phi^DY  ; iCor<-solve(Cor)
  V.beta<- solve( t(X)%*%iCor%*%X/s2 + T0)
  E.beta<- V.beta%*%( t(X)%*%iCor%*%y/s2  )
  beta<-t(rmvnorm(1,E.beta,V.beta)  )
  
  s2<-1/rgamma(1,(nu0+n)/2,(nu0*s20+t(y-X%*%beta)%*%iCor%*%(y-X%*%beta)) /2 )
  
  phi.p<-abs(runif(1,phi-.1,phi+.1))
  phi.p<- min( phi.p, 2-phi.p)
  lr<- -.5*( determinant(phi.p^DY,log=TRUE)$mod -
               determinant(phi^DY,log=TRUE)$mod  +
               sum(diag( (y-X%*%beta)%*%t(y-X%*%beta)%*%(solve(phi.p^DY) -solve(phi^DY)) ) )/s2 )
  
  if( log(runif(1)) < lr ) { phi<-phi.p ; ac<-ac+1 }
  
  if(s%%odens==0)
  {
    # cat(s,ac/s,beta,s2,phi,"\n") ;
    OUT<-rbind(OUT,c(beta,s2,phi))
  }
}

OUT.25000<-OUT
library(coda)
apply(OUT.25000,2,effectiveSize )
```

### Figure 10.9
```{r}
#### Figure 10.9
par(mar=c(3,3,1,1),mgp=c(1.75,.75,0))
par(mfrow=c(1,2))
plot(OUT.1000[,4],xlab="scan",ylab=expression(rho),type="l")
acf(OUT.1000[,4],ci.col="gray",xlab="lag")
```

### Figure 10.10
```{r}
#### Figure 10.10
par(mar=c(3,3,1,1),mgp=c(1.75,.75,0))
par(mfrow=c(1,2))
plot(OUT.25000[,4],xlab="scan/25",ylab=expression(rho),type="l")
acf(OUT.25000[,4],ci.col="gray",xlab="lag/25")
```

### Figure 10.11
```{r}
#### Figure 10.11
par(mar=c(3,3,1,1),mgp=c(1.75,.75,0))
par(mfrow=c(1,2))

plot(density(OUT.25000[,2],adj=2),xlab=expression(beta[2]),
     ylab="posterior marginal density",main="")

plot(y~X[,2],xlab=expression(CO[2]),ylab="temperature")
abline(mean(OUT.25000[,1]),mean(OUT.25000[,2]),lwd=2)
abline(lmfit$coef,col="gray",lwd=2)
legend(180,2.5,legend=c("GLS estimate","OLS estimate"),bty="n",
       lwd=c(2,2),col=c("black","gray"))
```

