---
title: "[ESC] Bayes Week2 HW"
author: "SonJiwoo"
date: '2021 1 13 '
output:
  pdf_document: null
  latex_engine: xelatex
mainfont: NanumGothic---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Bayesian Data Analysis
```{r}
library(tidyverse)
library(gridExtra)
```
  
## 2.11
#### (a)
```{r}
p1 <- data.frame(x=rep(seq(0, 100, 0.1),5)) %>% 
  mutate(y=rep(c(43,44,45,46.5,47.5),each=1001),
         pdf=dcauchy(y, location=x, scale=1)) %>%
  group_by(x) %>% 
  summarise(dense=prod(pdf)) %>%
  ggplot(aes(x=x, y=dense)) + geom_line() +
  ggtitle("Unnormalized Density")

p2 <- data.frame(x=rep(seq(0, 100, 0.1),5)) %>% 
  mutate(y=rep(c(43,44,45,46.5,47.5),each=1001),
         pdf=dcauchy(y, location=x, scale=1)) %>%
  group_by(x) %>% 
  summarise(dense.unnorm=prod(pdf)) %>% 
  mutate(dense.norm = dense.unnorm/sum(dense.unnorm)) %>%
  ggplot(aes(x=x, y=dense.norm)) + geom_line() +
  ggtitle("Normalized Density")

grid.arrange(p1, p2, ncol=2)
```

#### (b)
```{r}
df <- data.frame(x=rep(seq(0, 100, 0.1),5)) %>% 
  mutate(y=rep(c(43,44,45,46.5,47.5),each=1001),
         pdf=dcauchy(y, location=x, scale=1)) %>%
  group_by(x) %>% 
  summarise(dense.unnorm=prod(pdf)) %>% 
  mutate(dense.norm = dense.unnorm/sum(dense.unnorm))

theta.sample <- sample(df$x, size=1000, prob=df$dense.norm, replace=TRUE)
hist(theta.sample, xlab='theta', breaks=seq(0,100,0.1))
```

#### (c)
```{r}
y6 <- rcauchy(1000, theta.sample, 1)
hist(y6, nclass=1000, main='Histogram of Future Observation')
```

--- 

## Code Home Work

```{r}

```

