---
title: "[ESC] Bayes Week5 HW"
author: "SonJiwoo"
date: "`r Sys.Date()`"
output:
  pdf_document: null
  latex_engine: xelatex
mainfont: NanumGothic  
---

# Data Load
```{r load diabetes}
#### Diabetes example
load("data/diabetes.RData")
yf<-diabetes$y
yf<-(yf-mean(yf))/sd(yf)

Xf<-diabetes$X
Xf<-t( (t(Xf)-apply(Xf,2,mean))/apply(Xf,2,sd))
```

# Train-Test split
```{r}
## set up training and test data
n<-length(yf)
set.seed(1)

i.te<-sample(1:n,100)
i.tr<-(1:n)[-i.te]

y<-yf[i.tr] ; y.te<-yf[i.te]
X<-Xf[i.tr,]; X.te<-Xf[i.te,]
```

# Bayesian Model Selection
```{r}
#### Bayesian model selection
p<-dim(X)[2]
S<-10000

# source("regression_gprior.R")
lm.gprior<-function(y,X,g=dim(X)[1],nu0=1,s20=try(summary(lm(y~-1+X))$sigma^2,silent=TRUE),S=1000)
{

  n<-dim(X)[1] ; p<-dim(X)[2]
  Hg<- (g/(g+1)) * X%*%solve(t(X)%*%X)%*%t(X)
  SSRg<- t(y)%*%( diag(1,nrow=n)  - Hg ) %*%y

  s2<-1/rgamma(S, (nu0+n)/2, (nu0*s20+SSRg)/2 )

  Vb<- g*solve(t(X)%*%X)/(g+1)
  Eb<- Vb%*%t(X)%*%y

  E<-matrix(rnorm(S*p,0,sqrt(s2)),S,p)
  beta<-t(  t(E%*%chol(Vb)) +c(Eb))

  list(beta=beta,s2=s2)                                
}   

 
lmratio.gprior<-function(z0,z1,y,X,g=dim(X)[1],nu0=1,
                s200=mean( lm(y~-1+X[,z0==1])$res^2), 
                s201=mean( lm(y~-1+X[,z1==1])$res^2) ) 
{
  n<-dim(X)[1] 

  X0<-X[,z0==1]
  X1<-X[,z1==1]

  H0<- (g/(g+1)) * X0%*%solve(t(X0)%*%X0)%*%t(X0)
  SS0<- t(y)%*%( diag(1,nrow=n)  - H0 ) %*%y
  p0<-sum(z0==1) 

  H1<- (g/(g+1)) * X1%*%solve(t(X1)%*%X1)%*%t(X1)
  SS1<- t(y)%*%( diag(1,nrow=n)  - H1 ) %*%y
  p1<-sum(z1==1)  
 
   -.5*(p1-p0)*log( 2*pi*(1+g))  + 
    .5*nu0*log(s201/s200) + .5*(nu0+n)*log( (nu0*s200+SS0)/(nu0+s201+SS1) )
}




mselect.gprior<-function(y,X,S=500*dim(X)[2],verb=FALSE) 
{

  Z<-NULL
  z<-rep(1,dim(X)[2] )

  for(s in 1:S) 
  {
  
    for(j in sample(1:p)) 
    {
      z1<-z0<-z  ; z1[j]<-1 ; z0[j]<-0
      r<-lmratio.gprior(z0,z1,y,X)  
      z[j]<-rbinom(1,1,1/(1+exp(-r))) 
     } 
    Z<-rbind(Z,z) 
    if(verb==TRUE) {cat(s,mean(z),"\n") }
    }
  Z
} 

### need something for null model

lpy.X<-function(y,X,
   g=length(y),nu0=1,s20=try(summary(lm(y~-1+X))$sigma^2,silent=TRUE)) 
{
  n<-dim(X)[1] ; p<-dim(X)[2] 
  if(p==0) { s20<-mean(y^2) }
  H0<-0 ; if(p>0) { H0<- (g/(g+1)) * X%*%solve(t(X)%*%X)%*%t(X) }
  SS0<- t(y)%*%( diag(1,nrow=n)  - H0 ) %*%y

  -.5*n*log(2*pi) +lgamma(.5*(nu0+n)) - lgamma(.5*nu0)  - .5*p*log(1+g) +
   .5*nu0*log(.5*nu0*s20) -.5*(nu0+n)*log(.5*(nu0*s20+SS0))
}


####
mselect.gprior<-function(y,X,S=500*dim(X)[2],verb=FALSE) 
{

  Z<-NULL
  z<-rep(1,dim(X)[2] )

  for(s in 1:S)
  {

    for(j in sample(1:p))
    {
      z1<-z0<-z  ; z1[j]<-1 ; z0[j]<-0
      r<-lmratio.gprior(z0,z1,y,X)
      z[j]<-rbinom(1,1,1/(1+exp(-r)))
     }
    Z<-rbind(Z,z)
    if(verb==TRUE) {cat(s,mean(z),"\n") }
    }
  Z
}
#####

```


```{r}
## Don't run it again if you've already run it
runmcmc<-!any(system("ls",intern=TRUE)=="data/diabetesBMA.RData")
if(!runmcmc){ load("data/diabetesBMA.RData") }

if(runmcmc){
  
  BETA<-Z<-matrix(NA,S,p)
  z<-rep(1,dim(X)[2] )
  lpy.c<-lpy.X(y,X[,z==1,drop=FALSE])
  for(s in 1:S)
  {
    for(j in sample(1:p))
    {
      zp<-z ; zp[j]<-1-zp[j]
      lpy.p<-lpy.X(y,X[,zp==1,drop=FALSE])
      r<- (lpy.p - lpy.c)*(-1)^(zp[j]==0)
      z[j]<-rbinom(1,1,1/(1+exp(-r)))
      if(z[j]==zp[j]) {lpy.c<-lpy.p}
    }
    
    beta<-z
    if(sum(z)>0){beta[z==1]<-lm.gprior(y,X[,z==1,drop=FALSE],S=1)$beta }
    Z[s,]<-z
    BETA[s,]<-beta
    if(s%%10==0)
    { 
      bpm<-apply(BETA[1:s,],2,mean) ; plot(bpm)
      # cat(s,mean(z), mean( (y.te-X.te%*%bpm)^2),"\n")
      Zcp<- apply(Z[1:s,,drop=FALSE],2,cumsum)/(1:s)
      plot(c(1,s),range(Zcp),type="n") ; apply(Zcp,2,lines)
    }
  } 
  save(BETA,Z,file="diabetesBMA.RData")
}
```

### Figure 9.7
```{r}
#### Figure 9.7
par(mar=c(2.75,2.75,.5,.5),mgp=c(1.7,.7,0))

beta.bma<-apply(BETA,2,mean,na.rm=TRUE)
y.te.bma<-X.te%*%beta.bma
mean( (y.te-y.te.bma)^2)

layout( matrix(c(1,1,2),nrow=1,ncol=3) )

plot(apply(Z,2,mean,na.rm=TRUE),xlab="regressor index",ylab=expression(
  paste( "Pr(",italic(z[j] == 1),"|",italic(y),",X)",sep="")),type="h",lwd=2)

plot(y.te,y.te.bma,xlab=expression(italic(y)[test]),
     ylab=expression(hat(italic(y))[test])) ; abline(0,1)
```